[Metadata]
Name=macOS-Light-Blur
Version=1
Author=镜花水月
Description=macOS-style translucent candidate bar with dynamic background blur (light)
ScaleWithDPI=True

[InputPanel]
NormalColor=#3c3c43ff
HighlightColor=#ffffffff
HighlightCandidateColor=#ffffffff
HighlightBackgroundColor=#007affff
HighlightCandidateLabelColor=#ffffffff
CandidateLabelColor=#3c3c43ff
CandidateCommentColor=#6e6e73ff
CommentTextSizeFactor=75
FullWidthHighlight=False
PageButtonAlignment=Center
EnableBlur=True

[InputPanel/TextMargin]
Left=7
Right=7
Top=2
Bottom=2

[InputPanel/ContentMargin]
Left=8
Right=8
Top=5
Bottom=5

[InputPanel/Background]
Image=panel.svg

[InputPanel/Background/Margin]
Left=10
Right=10
Top=8
Bottom=8

[InputPanel/Highlight]
Image=highlight.svg

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=4
Bottom=4

[InputPanel/PrevPage]
Image=prev.svg

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=3
Bottom=3

[InputPanel/NextPage]
Image=next.svg

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=3
Bottom=3

[Menu]
NormalColor=#3c3c43ff
HighlightCandidateColor=#ffffffff
Spacing=2

[Menu/Background]
Color=#ffffffff
BorderColor=#c7c7ccff
BorderWidth=1

[Menu/Background/Margin]
Left=8
Right=8
Top=8
Bottom=8

[Menu/ContentMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu/CheckBox]
Image=radio.svg

[Menu/SubMenu]
Image=arrow.svg

[Menu/Highlight]
Color=#007affff

[Menu/Highlight/Margin]
Left=6
Right=6
Top=3
Bottom=3

[Menu/Separator]
Color=#d1d1d6ff

[Menu/TextMargin]
Left=6
Right=6
Top=3
Bottom=3

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
